---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check if my_fact is set
      assert:
        that:
          - ansible_local.custom.datacenter == "Amsterdam"
          - ansible_local.custom.availability_zone == "west"
